### ISSUE TITLE
Not quite sure how to run the script

### ISSUE THREAD

**Issue by C0deZLee** [fuxialexander/Applescript#1]
Hi, I'm very interested these scripts but I'm not sure how to run them, specifically, I don't know how to add a button on omnifocus toolbar and how to run those "osascript"
Could you give me a more detailed instruction?

**Comment by fuxialexander** [comment]
sorry for late reply, haven't checked github for some while... Basically, set up a new file in Script Editor, copy the content in the osascript file and save in identifiable name. Then put the file to while the omnifocus takes scripts (check the "open script folder" menu item in "Help" menu). After that, a new item will show up in the customisation panel of toolbar.

**Comment by C0deZLee** [comment]
Thanks! I figured it out!
