### ISSUE TITLE
My script doesn't work somehow

### ISSUE THREAD

**Issue by jktzes** [fuxialexander/Applescript#7]
Today I was just trying to explore the scripting functions of Omnifocus and stumbled across this Alfred [plugin](https://github.com/patrickkahl/alfred-tyme), after that I keep getting this error:

<img width="424" alt="screen shot 2018-02-27 at 7 59 14 pm" src="https://user-images.githubusercontent.com/17117898/36765826-b807f5b0-1bf8-11e8-84be-a8b76e5f1f48.png">

And then when I try to build the AppleScript, I got this: 

<img width="812" alt="screen shot 2018-02-27 at 7 55 32 pm" src="https://user-images.githubusercontent.com/17117898/36765837-c4beffce-1bf8-11e8-8915-2f2031eb2f27.png">

I guess it may not have anything to do with your script since I followed the instruction at the first time and it worked.

I also uninstalled the Alfred plugin I mentioned using npm.

Could you look into that?

**Comment by fuxialexander** [comment]
Has Tyme 2 updated their Applescript API? I haven't use Tyme 2 for a while thus I'm not sure what has been changed. Do you know any information about that?

**Comment by jktzes** [comment]
I really don't think so. Since I can use your old AppleScript just fine until 3 hours ago. BTW it was really useful, I should "buy you a coffee" or something if you have a link like that. I didn't do any updates, so it should't be the Tyme API.

**Comment by jktzes** [comment]
If you care to pay a visit to this project I would really appreciate it: https://github.com/patrickkahl/alfred-tyme.

**Comment by fuxialexander** [comment]
@jktzes Oh I see. You mean after you use that Alfred plugin things stopped to work right?

That's because both this script and that plugin relies on the applescript hook provided by Tyme 2: `tyme2_applescript_hooks.scpt/oascript` but we write that file differently. And after you install that plugin, the original file you put in the directory got overwritten.

In order to make both world work with each other, you need to merge the two `tyme2_applescript_hooks.scpt` file, by copying the content of the corresponding function/hook from one file to the other. 

For example:
change
```Applescript
on timerStartedForTaskRecord(tskRecordID)
	tell application "Tyme2"
		GetRecordWithID tskRecordID
		set tskID to relatedTaskID of lastFetchedTaskRecord
		set tsk to the first item of (every task of every project whose id = tskID)
		set tskName to name of tsk
		say tskName
	end tell
end timerStartedForTaskRecord
```

to

```Applescript
on timerStartedForTaskRecord(tskRecordID)
	tell application "Tyme2"
		GetRecordWithID tskRecordID
		set tskID to relatedTaskID of lastFetchedTaskRecord
		set tsk to the first item of (every task of every project whose id = tskID)
		set tskName to name of tsk
		say tskName
	end tell
        tell application "Alfred 3" to run trigger "reload" in workflow "com.patrickkahl.tyme" with argument "cache:updateTaskForTaskRecordId:" & tskRecordID
end timerStartedForTaskRecord
```

**Comment by lrrrs** [comment]
I'm sorry, there was an issue with the hooks in the last release. The update just went live: 2018.7

**Comment by jktzes** [comment]
Yeah everything is working with each other beautifully right now. Thanks folks! @fuxialexander @lrrrs
